# Perceptron 

Treinamento de um perceptron para classificação de imagens preto e branco, representadas por uma matriz de pixels 3x3, em "clara" ou "escura".
 - Pixels brancos = 1 e pixels pretos = -1

Fonte: [Link](https://edisciplinas.usp.br/pluginfile.php/4457290/mod_resource/content/2/SIN5007-Tema08-RedesNeurais.pdf)

In [1]:
# Dados iniciais
import numpy as np

# Base de dados
# Classe 1 (predominantemente branca)
A = np.array( [1, -1, 1, -1, 1, 1, -1, -1, 1] )

# Classe -1 (predominantemente preta)
B = np.array( [-1, -1, -1, 1, -1, 1, 1, 1, -1] )

# Classe 1 (predominantemente branca)
C = np.array( [1, -1, 1, 1, -1, 1, -1, 1, 1] )

# Pesos iniciais (pesos igual para que as entradas tenha mesma relevância)
Pesos = np.array( [0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11] )

# Taxa de aprendizagem
eta = 0.1

# Viés
bias = -0.5

In [2]:
# Função para a soma ponderada
# u = x0*w0 + x1*w1 + x2*w2 + 1*θ
# m = x0*w0 + x1*w1 + x2*w2
# u = m + 1*θ

def somaPonderada(X, W):
  bias = -0.5
  m = np.multiply(X, W)
  u = np.sum(m) + 1*bias
  return u

In [3]:
# Função de ativação
# Função Degrau

def funcaoAtivacao(u):
  if u >= 0:
    return 1
  else:
    return -1

In [4]:
# Função de saída

def saida(X, W):
  u = somaPonderada(X, W)
  return funcaoAtivacao(u)

In [5]:
# Função para ajustes dos pesos
# Parte central do processo de aprendizagem
# Novo wi  →  wi = wi +  η xi (d - y)

def ajustaPesos(eta, W, X, bias, d, y):
  e = d - y
  novoW = W + eta*X*e
  novoB = bias + eta*(-1)*e
  return novoW, novoB

# Treinamento 
* Realizado manualmente para ilustrar o processo 
* Aprsenta uma entrada e calcula a saída de maneira iterativa 

## Iteração 1

In [6]:
# Entrada predominantemente branca saída +1
d = 1
y = saida(A, Pesos)
print(y)
# Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, A, bias, d, y)
print(Pesos)
print(bias)

print("-----")

# Entrada predominantemente preta saída -1
d = -1
y = saida(B, Pesos)
print(y)
#Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, B, bias, d, y)
print(Pesos)
print(bias)

print("-----")

# Entrada predominantemente branca saída +1
d = 1
y = saida(C, Pesos)
print(y)
#Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, C, bias, d, y)
print(Pesos)
print(bias)

-1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7
-----
-1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7
-----
1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7


## Iteração 2

In [7]:
# Entrada predominantemente branca saída +1
d = 1
y = saida(A, Pesos)
print(y)
# Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, A, bias, d, y)
print(Pesos)
print(bias)

print("-----")

# Entrada predominantemente preta saída -1
d = -1
y = saida(B, Pesos)
print(y)
#Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, B, bias, d, y)
print(Pesos)
print(bias)

print("-----")

# Entrada predominantemente branca saída +1
d = 1
y = saida(C, Pesos)
print(y)
#Ajuste dos pesos
Pesos, bias = ajustaPesos(eta, Pesos, C, bias, d, y)
print(Pesos)
print(bias)

1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7
-----
-1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7
-----
1
[ 0.31 -0.09  0.31 -0.09  0.31  0.31 -0.09 -0.09  0.31]
-0.7


# Teste
* A que classe pertencem os padrões 111, 000, 100 e 011?

In [8]:
# Padrão "claro"
T = np.array( [1, 1, 1, -1, 1, 1, 1, -1, 1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [ 1  1  1 -1  1  1  1 -1  1]  é  1


In [9]:
# Padrão "escuro"
T = np.array( [-1, -1, 1, -1, -1, -1, -1, -1, 1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [-1 -1  1 -1 -1 -1 -1 -1  1]  é  -1


In [10]:
# Padrão "claro"
T = np.array( [1, 1, 1, 1, 1, 1, -1, 1, 1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [ 1  1  1  1  1  1 -1  1  1]  é  1


In [14]:
# Padrão "escuro"
T = np.array( [1, -1, -1, -1, 1, -1, -1, -1, -1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [ 1 -1 -1 -1  1 -1 -1 -1 -1]  é  -1


In [15]:
# Padrão "claro"
T = np.array( [-1, -1, 1, -1, 1, 1, 1, -1, 1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [-1 -1  1 -1  1  1  1 -1  1]  é  1


In [16]:
# Padrão "claro"
T = np.array( [-1, -1, -1, 1, 1, 1, 1, -1, 1] )
print("Saida para ", T, " é ", saida(T, Pesos))

Saida para  [-1 -1 -1  1  1  1  1 -1  1]  é  -1
